// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order/proto/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_order_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_order_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_order_proto_order_proto protoreflect.FileDescriptor

const file_order_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x17order/proto/order.proto\x12\x05hello\"(\n" +
	"\x12CreateOrderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10CreateOrderReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2S\n" +
	"\fOrderService\x12C\n" +
	"\vCreateOrder\x12\x19.hello.CreateOrderRequest\x1a\x17.hello.CreateOrderReply\"\x00B\x15Z\x13./order/proto;orderb\x06proto3"

var (
	file_order_proto_order_proto_rawDescOnce sync.Once
	file_order_proto_order_proto_rawDescData []byte
)

func file_order_proto_order_proto_rawDescGZIP() []byte {
	file_order_proto_order_proto_rawDescOnce.Do(func() {
		file_order_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_order_proto_rawDesc), len(file_order_proto_order_proto_rawDesc)))
	})
	return file_order_proto_order_proto_rawDescData
}

var file_order_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_proto_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil), // 0: hello.CreateOrderRequest
	(*CreateOrderReply)(nil),   // 1: hello.CreateOrderReply
}
var file_order_proto_order_proto_depIdxs = []int32{
	0, // 0: hello.OrderService.CreateOrder:input_type -> hello.CreateOrderRequest
	1, // 1: hello.OrderService.CreateOrder:output_type -> hello.CreateOrderReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_proto_order_proto_init() }
func file_order_proto_order_proto_init() {
	if File_order_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_order_proto_rawDesc), len(file_order_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_order_proto_goTypes,
		DependencyIndexes: file_order_proto_order_proto_depIdxs,
		MessageInfos:      file_order_proto_order_proto_msgTypes,
	}.Build()
	File_order_proto_order_proto = out.File
	file_order_proto_order_proto_goTypes = nil
	file_order_proto_order_proto_depIdxs = nil
}
