kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
#      hostNetwork: true
      containers:
        - name: hello
          image: echomusic/hello:v2.0
          ports:
            - containerPort: 8090
#              protocol: TCP