kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      #      hostNetwork: true
      containers:
        - name: order
          image: echomusic/order:v2.0
          ports:
            - containerPort: 50051
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - name: order
      port: 50051          # 服务端口
      targetPort: 50051    # 容器端口
      protocol: TCP
  type: ClusterIP       # 内部集群访问

