apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8090        # 前台接待
      targetPort: 8090  # 服务提供者(按摩，推拿)
      nodePort: 30000   # 如果 type 是 NodePort，需要指定 nodePort
  type: NodePort  # 或者 LoadBalancer